import { AppError } from '../../domain/clothme.shared.kernel/error/AppError';
import { AppState, ApiStatus } from './AppState';

export const InitialState: AppState = {
  signUpState: {
    loadingStatus: ApiStatus.LOADING,
    addingStatus: ApiStatus.LOADED,
    isSuccess: false,
    errorMessage: '',
  },

  companyState: {
    companyId: '',
    companyName: '',
    locations: [],
    brands: [],
    companyContact: [{}],
    removed: false,
  },

  locationState: {
    locationId: '',
    locationName: '',
    locationAddress: {},
    companyId: '',
    locationLogo: '',
    locationContact: [{}],
    published: false,
    removed: false,
  },

  brandState: {
    brandId: '',
    brandName: '',
    brandGender: '',
    companyId: '',
    brandLogo: '',
    brandDemography: '',
    brandLaunchDate: '',
    locationId: '',
    brandContact: [{}],
    published: false,
    removed: false,
  },

  employeeState: {
    employeeId: '',
    email: '',
    firstName: '',
    lastName: '',
    token: '',
    phoneNumber: '',
    dateOfBirth: '',
    locationId: '',
    companyId: '',
    employeeDuties: [{}],
    employeeRoles: [{}],
    terminated: false,
    suspended: false,
    success: false,
  },

  productState: {
    productId: '',
    productName: '',
    productDescription: '',
    productImages: [''],
    defaultImage: '',
    gender: '',
    measurement: {},
    price: 0,
    discount: [{}],
    productCategory: '',
    productCatergoryType: '',
    fabric: '',
    returns: '',
    delivery: '',
    tax: 0,
    likeCount: 0,
    reviews: [{}],
    averageReview: 0,
    reviewCount: 0,
    published: false,
    removed: false,
  },

  accountState: {},
  promotion: {},
  shippingState: {},
  orderState: {},
  customerServiceState: {},
  salesReportState: {},
  customerReportState: {},
  productReportState: {},
};
